export const Data = {
scooters:[
  {
    id:1,
    name:"OLA S1 Pro",
    images:{
        default:"../assets/images/Products-Images/ola s1 pro.webp",
        AMETHYST:  "../assets/images/Products-Images/ola s1 pro Amethyst.webp",
        STELLARBLUE:  "../assets/images/Products-Images/ola s1 pro StellarBlue.webp",
        MATTWHITE:  "../assets/images/Products-Images/ola s1 pro MatteWhite.webp",
        JETBLACK:  "../assets/images/Products-Images/ola s1 pro JetBlack.webp",
        MIDNIGHTBLUE:  "../assets/images/Products-Images/ola s1 pro MidnightBlue.webp", },
    Colours:{
            AMETHYST:"#9966CC",
            STELLARBLUE:"#4682B4",
            JETBLACK:"#000000",
             MATTWHITE:"#F5F5F5",
            MIDNIGHTBLUE:"#191970",},

     variants: [
            {
              battery: "4kWh",
              price:  "₹1,34,999",
              range: "195 km",
              chargingTime: "4.5 Hour",
              topspeed: "120 km/h",
              acceleration: "2.6 sec",
            },
          ],

    specifications:{
        Modes:["Eco","Normal","Sports","Hyper"],
        fastcharging:"Yes",
        BootSpace:"34 L",
        KeyType:"Digital Key",
        Bluetooth:"Yes",
        GPSConnectivity:"Yes",
        warranty:"3 yrs/50,000 kms",
        PeakPower:"11 kW",
        Instrumentcluster:"17.78 cm (7) Touch screen",
        MotorType:"Mid Drive IPM",
        ChargerTypeCapacity:"Portable 750 W",
        BrakeType:"Disc Brake",
        CruiseControl:"YES",
        WheelType:"Alloy Wheel",
        tyretype:"Tubeless",
        hello:"hi",},
     },
  {
    id:2,
    name:"OLA S1 Air",
    images:{
        default:"../assets/images/Products-Images/ola s1 air.webp",
        CORALGLAM:  "../assets/images/Products-Images/ola s1 air CoralGlam.webp",
        STELLERBLUE:  "../assets/images/Products-Images/ola s1 air StellarBlue.webp",
        PORCELAINWHITE:  "../assets/images/Products-Images/ola s1 air PorcelainWhite.webp",
        LIQUIDSILVER:  "../assets/images/Products-Images/ola s1 air LiquidSilver.webp",
        MIDNIGHTBLUE:  "../assets/images/Products-Images/ola s1 air MidnightBlue.webp",
        NEON: "../assets/images/Products-Images/ola s1 air Neon.webp",
        }, 
    Colours:{
            CORALGLAM:"#FF0000",
            LIQUIDSILVER:"#C0C0C0",
             MIDNIGHTBLUE:"#191970",
            PORCELAINWHITE:"#F5F5F5",
            STELLERBLUE:"#1E3A5F ",
            NEON:"#c8ff14a9",},

    variants: [
            {
              battery: "4kWh",
              price: "₹1,20,000",
              range: "165  km",
              chargingTime: "4.5 hours",
              topspeed: "90 km/h",
              acceleration: "3.3 sec",
            },
            {
              battery: "3kWh",
              price: "₹99,999",
              range: "125  km",
              chargingTime: "4.2 hours",
              topspeed: "90 km/h",
              acceleration: "3.3 sec",
            },
            {
              battery: "2kWh",
              price: "₹84,999",
              range: "85  km",
              chargingTime: "3.5 hours",
              topspeed: "90 km/h",
              acceleration: "3.3 sec",
            },
          ],

    specifications:{
        Modes:["Eco","Normal","Sports"],
        fastcharging:"Yes",
        BootSpace:"34 L",
        KeyType:"Digital Key",
        Bluetooth:"Yes",
        GPSConnectivity:"Yes",
        warranty:"3 yrs/50,000 kms",
        PeakPower:"6 kW",
        Instrumentcluster:"12.7 cm (5)/ Segmented LCD",
        MotorType:"Hub Motor",
        ChargerTypeCapacity:"Portable 750 W",
        BrakeType:"Drum Brake",
        CruiseControl:"YES",
        WheelType:"Steel  Wheel",
        tyretype:"Tubeless"},
     },
    {
    id:3,
    name:"OLA S1 x",
    images:{
        default:"../assets/images/Products-Images/ola s1 x.webp",
        REDVELOCITY:  "../assets/images/Products-Images/ola s1 x Red Velocity.webp",
        STELLERBLUE:  "../assets/images/Products-Images/ola s1 x Steller.webp",
        PORCELAINWHITE:  "../assets/images/Products-Images/ola s1 x PorcelainWhite.webp",
        VOUGE :  "../assets/images/Products-Images/ola s1 x liquidsilver.webp",
        MIDNIGHTBLUE:  "../assets/images/Products-Images/ola s1 x Midnight.webp",
        FUNK:  "../assets/images/Products-Images/ola s1 x Funk.webp",
        LIQUIDSILVER:  "../assets/images/Products-Images/ola s1 x Vouge.webp",
        }, 
     Colours:{
            REDVELOCITY:"#FF0000",
            VOUGE:"#C0C0C0",
            PORCELAINWHITE:"#F5F5F5",
            MIDNIGHTBLUE:"#191970",
            FUNK:"#c8ff14a9",
            LIQUIDSILVER:"#8f9285a9",
            STELLERBLUE:"#1E3A5F ",},

     variants: [
            {
              battery: "4kWh",
              price: "₹1,10,000",
              range: "190  km",
              chargingTime: "6.5 hours",
              topspeed: "90 km/h",
              acceleration: "4.1 sec",
            },
            {
              battery: "3kWh",
              price: "₹89,999",
              range: "141  km",
              chargingTime: "7.4 hours",
              topspeed: "90 km/h",
              acceleration: "4.1 sec",
            },
            {
              battery: "2kWh",
              price: "₹79,999",
              range: "90  km",
              chargingTime: "5 hours",
              topspeed: "90 km/h",
              acceleration: "4.1 sec",
            },
          ],
        
     specifications:{
        Modes:["Eco","Normal","Sports"],
        fastcharging:"Yes",
        BootSpace:"34 L",
        KeyType:"Physical Key",
        Bluetooth:"No",
        GPSConnectivity:"No",
        warranty:"3 yrs/50,000 kms",
        PeakPower:"6 kW",
        Instrumentcluster:"10.92 cm (4.3) Segmented LCD",
        MotorType:"Hub Motor",
        ChargerTypeCapacity:"Portable 750 W",
        BrakeType:"Drum Brake",
        CruiseControl:"YES",
        WheelType:"Steel  Wheel",
        tyretype:"Tubeless"},
     }],
bikes:[{
     id:4,
     name:"ROADSTER X",
     images:{default:"../assets/images/Products-Images/roadster x.webp",},
     variants: [
        {
          battery: "4.5kWh",
          price: "₹99,999",
          range: "200  km",
          chargingTime: "5.9 hours",
          topspeed: "124 km/h",
          acceleration: "2.8 sec",
        },
        {
          battery: "3.5kWh",
          price: "₹84,999",
          range: "159  km",
          chargingTime: "4.6 hours",
          topspeed: "117 km/h",
          acceleration: "2.9 sec",
        },
        {
          battery: "2.5kWh",
          price: "₹74,999",
          range: "117  km",
          chargingTime: "3.3 hours",
          topspeed: "105 km/h",
          acceleration: "3.2 sec",
        },],
     specifications:{
            Modes:["Eco","Normal","Sports"],
            fastcharging:"Yes",
            BootSpace:"* N *",
            KeyType:"Physical Key",
            Bluetooth:"No",
            GPSConnectivity:"No",
            warranty:"3 yrs/50,000 kms",
            PeakPower:"11 kW",
            Instrumentcluster:"4.3 inch Segmented LCD",
            MotorType:"Mid Drive IPM",
            ChargerTypeCapacity:"Portable 750 W",
            BrakeType:"Disc Brake",
            CruiseControl:"YES",
            WheelType:"Alloy  Wheel",
            tyretype:"Tubeless"},
},{
     id:5,
     name:"ROADSTER",
     images:{default:"../assets/images/Products-Images/roadster.webp",},
   
     variants: [
        {
          battery: "6kWh",
          price: "₹1,39,999",
          range: "248  km",
          chargingTime: "7.9 hours",
          topspeed: "126 km/h",
          acceleration:"2.2 sec",
        },
        {
          battery: "4.5kWh",
          price: "₹1,19,999",
          range: "190  km",
          chargingTime: "5.9 hours",
          topspeed: "126 km/h",
          acceleration: "2.2 sec",
        },
        {
          battery: "3.5kWh",
          price: "₹1,04,999",
          range: "151  km",
          chargingTime: "4.6 hours",
          topspeed: "116 km/h",
          acceleration: "2.4 sec",
        },
       ],
       specifications:{
        Modes:["Eco","Normal","Sports","Hyper"],
        fastcharging:"Yes",
        BootSpace:"* N *",
        KeyType:"Physical Key",
        Bluetooth:"Yes",
        GPSConnectivity:"Yes",
        warranty:"3 yrs/50,000 kms",
        PeakPower:"13 kW",
        Instrumentcluster:"7 inch TFT With Touch",
        MotorType:"Mid Drive IPM",
        ChargerTypeCapacity:"Portable 750 W",
        BrakeType:"Disc Brake ABS",
        CruiseControl:"YES",
        WheelType:"Diamond Cut Alloy Wheel",
        tyretype:"Tubeless"},
},{
     id:6,
     name:"ROADSTER PRO",
     images:{default:"../assets/images/Products-Images/roadster pro.webp"},
     variants: [
        {
          battery: "16kWh",
          price: "₹2,49,999",
          range: "579  km",
          chargingTime: "7.5 Hours",
          topspeed: "194 km/h",
          acceleration: "1.2 sec",
        },
        {
          battery: "8kWh",
          price: "₹1,99,999",
          range: "316  km",
          chargingTime: "6.5 Hours",
          topspeed: "154 km/h",
          acceleration: "1.2 sec",
        },],
        specifications:{
            Modes:["Eco","Normal","Sports","Hyper"],
            fastcharging:"Yes",
            BootSpace:"* N *",
            KeyType:"  Digital Key",
            Bluetooth:"Yes",
            GPSConnectivity:"Yes",
            warranty:"3 yrs/50,000 kms",
            PeakPower:"52 kW",
            Instrumentcluster:" 10 inch Touchscreen TFT Display",
            MotorType:"Mid Drive IPM",
            ChargerTypeCapacity:"Portable 2.2 kW",
            BrakeType:" Dual Disc Brake ABS ",
            ADAS:"ADAS Level 1",
            CruiseControl:"YES",
            WheelType:"Diamond Cut Alloy Wheel",
            tyretype:"Tubeless"},
    
    }],
gigs:[{
    id:7,
    name:"OLA Gig",
    images:{default:"../assets/images/Products-Images/ola gig.webp"},
    variants: [
        {
          battery: "1.5kWh * 1",
          price:  "₹39,999",
          range: "112 km",
          chargingTime: " *Portable Battery*",
          topspeed: "25 km/h",
          acceleration: "* N *",
        },
      ],
},{
    id:8,
    name:"OLA Gig+",
    images:{default:"../assets/images/Products-Images/ola gig +.webp",},
    variants: [
        {
          battery: "1.5kWh * 2",
          price:  "₹49,999",
          range: "80 / 157 km",
          chargingTime: " *Portable Battery*",
          topspeed: "45 km/h",
          acceleration:  "* N *",
        },
      ],
}],
new:[{ 
    id:8,
    name:"OLA s1 Z",
    images:{default:"../assets/images/Products-Images/ola s1 z.webp"},
    variants: [
        {
          battery: "1.5kWh x 2",
          price:  "₹59,999",
          range: "75 / 146 km",
          chargingTime: " *Portable Battery*",
          topspeed: "70 km/h",
          acceleration: "* N *",
        },
      ],
    },
     { 
    id:9,
    name:"OLA s1 Z+",
    images:{default:"../assets/images/Products-Images/ola s1 z+.webp"},
    variants: [
        {
          battery: "1.5kwh  X 2",
          price:  "₹59,999",
          range: "75 / 146 km",
          chargingTime: " *Portable Battery*",
          topspeed: "70 km/h",
          acceleration: "* N *",
        },
      ],
    }],

};
